### ISSUE TITLE
Cant login

### ISSUE THREAD

**Issue by motxumotxu2** [uoinfusion/Infusion#135]
Hello
When trying to connect to server always throw this exception:
23:12:12:521 - Connection to client lost. Please restart infusion.
Any ideas?
Ty

**Comment by JakubLinhart** [comment]
Thank you for reporting it. I know about similar issue, but it doesn't happen always, just sometimes. It will be fixed in the next release, but I cannot guarantee that it helps with your problem.

What client (and version) do you use? What server do you play on?

Please, could you write `,console-show-all` to the console and copy content, paste it to a file and attach it to this issue?

**Comment by JakubLinhart** [comment]
A fix for the problem I have found will be included in 1.0.64 (will be released at the end of this week or in the next week). It could help you but not necessary.

**Comment by motxumotxu2** [comment]
7.0.20.0 patch 59.
ill try with new release and feedback
ty

**Comment by motxumotxu2** [comment]
System.InvalidOperationException: Encryption not recognized.
   en Infusion.IO.Encryption.Login.LoginEncryptionDetector.Detect(UInt32 seed, IPullStream inputStream) en c:\Users\jakub\sources\ultima\Infusion\src\Infusion\IO\Encryption\Login\LoginEncryptionDetector.cs:línea 32
   en Infusion.UltimaClientConnection.DetectEncryption(IDiagnosticPullStream inputStream) en c:\Users\jakub\sources\ultima\Infusion\src\Infusion\UltimaClientConnection.cs:línea 113
   en Infusion.UltimaClientConnection.ReceiveBatch(IPullStream inputStream, Int32 batchLength) en c:\Users\jakub\sources\ultima\Infusion\src\Infusion\UltimaClientConnection.cs:línea 71
   en Infusion.Proxy.Program.ClientLoop(ILogger packetLogger) en c:\Users\jakub\sources\ultima\Infusion\src\Infusion.Proxy\Program.cs:línea 196

**Comment by motxumotxu2** [comment]
Tried 1.0.63

19:22:12:619 - 20/03/2019
19:22:12:619 - Infusion 1.0.63.0
19:22:12:621 - Infusion root path D:\Infusion-1.0.63-alpha
19:22:23:490 - Loading mul files from C:\Program Files (x86)\UOInfinity.
19:22:23:589 - Configuring server address: C:\Program Files (x86)\UOInfinity\login.cfg
19:22:23:594 - Configuring user name and password: C:\Program Files (x86)\UOInfinity\uo.cfg
19:22:23:599 - Staring C:\Program Files (x86)\UOInfinity\NoCryptClient.exe from C:\Program Files (x86)\UOInfinity
19:22:23:753 - Executing file D:\Infusion-1.0.62-alpha\scripts\startup.csx.
19:22:24:647 - OK (in 893 ms)
19:22:31:508 - Connecting to play.uoinfinity.com,2593
19:22:31:655 - Connection to client lost. Please restart infusion.
19:22:31:655 - 
19:22:31:658 - System.IndexOutOfRangeException: Índice fuera de los límites de la matriz.
   en Infusion.IO.Encryption.NewGame.TwofishEncryption..ctor(Int32 keyLen, Byte[] key, Byte[] iv, CipherMode cMode, EncryptionDirection direction) en c:\Users\jakub\sources\ultima\Infusion\src\Infusion\IO\Encryption\NewGame\TwoFishEncryption.cs:línea 26
   en Infusion.IO.Encryption.NewGame.NewGameCrypt.Initialize() en c:\Users\jakub\sources\ultima\Infusion\src\Infusion\IO\Encryption\NewGame\NewGameCrypt.cs:línea 54
   en Infusion.IO.Encryption.NewGame.NewGameCrypt..ctor(Byte[] cryptoKey) en c:\Users\jakub\sources\ultima\Infusion\src\Infusion\IO\Encryption\NewGame\NewGameCrypt.cs:línea 24
   en Infusion.IO.Encryption.NewGame.ServerNewGamePullStream..ctor(Byte[] cryptoKey) en c:\Users\jakub\sources\ultima\Infusion\src\Infusion\IO\Encryption\NewGame\ServerNewGamePullStream.cs:línea 10
   en Infusion.ServerConnection.InitNewGameEncryption(Byte[] key) en c:\Users\jakub\sources\ultima\Infusion\src\Infusion\ServerConnection.cs:línea 159
   en Infusion.Proxy.Program.ClientConnectionOnNewGameEncryptionStarted(Byte[] key) en c:\Users\jakub\sources\ultima\Infusion\src\Infusion.Proxy\Program.cs:línea 398
   en Infusion.UltimaClientConnection.ReceiveSeed(IPullStream inputStream, Int32 batchLength, UltimaClientConnectionStatus nextStatus) en c:\Users\jakub\sources\ultima\Infusion\src\Infusion\UltimaClientConnection.cs:línea 215
   en Infusion.UltimaClientConnection.ReceiveBatch(IPullStream inputStream, Int32 batchLength) en c:\Users\jakub\sources\ultima\Infusion\src\Infusion\UltimaClientConnection.cs:línea 73
   en Infusion.Proxy.Program.ClientLoop(ILogger packetLogger) en c:\Users\jakub\sources\ultima\Infusion\src\Infusion.Proxy\Program.cs:línea 200
19:22:34:889 - ,console-show-all

**Comment by JakubLinhart** [comment]
Thanks! I guess UO Infinity is powered by RunUO, so it doesn't use encryption. This issue is most likely related to that. I'm going to test it and I will add the fix into the next release.

**Comment by JakubLinhart** [comment]
Maybe for now you could workaround this problem by using [CrossUO](https://github.com/crossuo/crossuo/releases/tag/1.0.1) instead of the classic client.

**Comment by JakubLinhart** [comment]
There were many problems when connecting to UOInfinity. I'm now able to login to the game. You have to use this configuration for UOInfinity:
![image](https://user-images.githubusercontent.com/1675735/54883335-34711380-4e65-11e9-96e2-f34cc402782c.png)

The fix will be available in version 1.0.64 which should be released soon, maybe tomorrow.
