### ISSUE TITLE
Disconnect after Launch

### ISSUE THREAD

**Issue by Kagoul** [uoinfusion/Infusion#157]
disconnects if I do not log in within +-10 seconds after launch the client.

23:23:00:149 - Configuring server address: C:\Program Files (x86)\Electronic Arts\Ultima Online Classic\login.cfg
23:23:00:166 - Configuring user name and password: C:\Program Files (x86)\Electronic Arts\Ultima Online Classic\uo.cfg
23:23:00:181 - Staring C:\Program Files (x86)\Electronic Arts\Ultima Online Classic\client.exe from C:\Program Files (x86)\Electronic Arts\Ultima Online Classic
23:23:13:735 - Connecting to login.ultimaonline.com,7776
23:23:13:737 - Disconnected from server. Please, restart Infusion.
23:23:13:752 - Detected client version: 7.0.75.35

**Comment by JakubLinhart** [comment]
Fix will be in 1.0.68.
