### ISSUE TITLE
The type or namespace name 'IScriptEngine' does not exist in the namespace 'RoslynPad.UI'

### ISSUE THREAD

**Issue by rrivani** [uoinfusion/Infusion#166]
Full error in VS Studio Community 2019 v.16, project Infusion.Desktop:
_The type or namespace name 'IScriptEngine' does not exist in the namespace 'RoslynPad.UI' (are you missing an assembly reference?)_	

The file is RoslynPadScriptEngineBridge.cs, line 21.

`using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Diagnostics;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;
using Infusion.Commands;
using Infusion.EngineScripts;
using Infusion.LegacyApi;
using Infusion.LegacyApi.Console;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Scripting;
using Microsoft.CodeAnalysis.Scripting;
using Microsoft.CodeAnalysis.Text;

namespace Infusion.Desktop.Scripts
{
    public class RoslynPadScriptEngineBridge : **RoslynPad.UI.IScriptEngine**`

**Comment by JakubLinhart** [comment]
Thank you for the report. Please, could you check if you have RoslynPad switched to `infusion-1.0.45` branch or better to your `rrivani:fix-build-errors`?

The new developer experience for Infusion is awful, I will try to prepare a script to setup the dev environment properly.

**Comment by rrivani** [comment]
Thanks @JakubLinhart ! Switching to infusion-1.0.45 branch solved the errors.
