### ISSUE TITLE
Fails to launch

### ISSUE THREAD

**Issue by JamesRoche** [uoinfusion/Infusion#174]
I am unable to get this to launch ClassicUO it just closes.

I am doing the following

Running as admin
Set server and port
Set USername
Set ClassicUO as client

Clicking Launch. No errors occur and it looks like it working then it just closes.
![Infusion Desktop_SxZveYT9bi](https://user-images.githubusercontent.com/1644288/111898003-1b32db80-8a1b-11eb-8a0c-dc3f192cf82f.jpg)

**Comment by 3HMonkey** [comment]
Standard CUO client is not working without start parameters. When you try to start the client without anything (means also without Infusion) the client just closes. I think that Outlands is trying to prevent other assists than Razor.

**Comment by JamesRoche** [comment]
Is there start parameters i can pass in, im not used to CUO yet as was previously using orion.

**Comment by 3HMonkey** [comment]
I think they compiled ClassicUO theirself. It seems that it is also ignoring the settings.json in CUO path. Also using CUO from out of outlands"Normal" folder lets you login but hangs on verification screen. I have to find out why. Like I said... maybe they ahve a custom build.

**Comment by JamesRoche** [comment]
Yeah I have tried compiling classicuo myself and connecting and it hangs on entering. Do you have Discord?

**Comment by 3HMonkey** [comment]
Yes I have :) btw they have their own login routine coded in their custom compile to prevent everyone from cheating.

**Comment by 3HMonkey** [comment]
Approved
